project:
  type: website

website:
  title: "Chaoyue Wang"
  description: "Chaoyue Wang's Personal Website"
  favicon: icon.png
  page-footer:
    right:
      - icon: envelope
        href: mailto:chyrwang@gmail.com
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
    left: "{{< fa copyright >}} 2022, Chaoyue Wang. Proudly Build with Quarto through RStudio."
  navbar:
    foreground: light
    left:
      - href: about.qmd
        text: About
      - research.qmd
      - data.qmd
      - software.qmd
      - href: graphics.qmd
        text: Graphics
    right: 
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
  

format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css

editor: visual

