project:
  type: website
  resources: 
  - "assets/"
  - "research/"

website:
  title: "CHAOYUE"
  description: "Chaoyue Wang's Personal Website"
  favicon: icon.png
  search: 
    type: textbox

  page-footer:
    center: "**Chaoyue Wang {{< fa solid copyright >}} 2023. Built with Quarto.**"
      # - icon: twitter
      #   href: https://twitter.com/raphael_cwang
      # - icon: github
      #   href: https://github.com/Raphaellie
      # - icon: envelope
      #   href: mailto:chyrwang@gmail.com

  navbar:
    title: "[**Chaoyue Wang**]{.smallcaps}"
    logo: icon2.png
    background: dark
    foreground: light
    pinned: true
    left:
      - href: index.qmd
        text: "About" # {{< fa solid circle-user >}} 
      - href: research.qmd
        text: "Research" # {{< fa cube >}}
      # - href: data.qmd
        # text: "Data" # {{< fa database >}}
      - href: software.qmd
        text: "Software" # {{< fa solid floppy-disk >}} 
      # - href: graphics.qmd
      #   text: "{{< fa chart-bar >}} Graphics"
      - href: posts.qmd
        text: "Posts" # {{< fa solid fire >}} 
      - icon: envelope-fill
        href: mailto:chyrwang@gmail.com
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie


format:
  html:
    theme: sandstone
    # fontcolor: "#222222"
    linkcolor: $primary
    fontsize: 100% # 95%
    # backgroundcolor: white
    # css: styles.css

editor: visual