project:
  type: website
  resources: 
  - "assets/"
  - "research/"

website:
  title: "CHAOYUE"
  description: "Chaoyue Wang's Personal Website"
  favicon: icon.png
  search: 
    type: textbox
  
  page-footer:
    right:
      - icon: envelope
        href: mailto:chyrwang@gmail.com
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
    left: "Chaoyue Wang {{< fa solid copyright >}} 2022. Proudly Built with Quarto and {{< fa heart >}} through RStudio."
  
  navbar:
    title: "CHAOYUE WANG"
    logo: icon.png
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: "{{< fa regular address-card >}} About"
      - href: research.qmd
        text: "{{< fa burst >}} Research"
      - href: data.qmd
        text: "{{< fa database >}} Data"
      - href: software.qmd
        text: "{{< fa window-restore >}} Software"
      # - href: graphics.qmd
      #   text: "{{< fa chart-bar >}} Graphics"
      - href: blog.qmd
        text: "{{< fa regular comment >}} Blog"
    right: 
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie

format:
  html:
    theme: 
      light: [journal, light.scss]
      dark: [journal, deep.scss]
    css: styles.css

editor: visual