project:
  type: website
  resources: 
  - "assets/"
  - "research/"

website:
  title: "CHAOYUE"
  description: "Chaoyue Wang's Personal Website"
  favicon: icon.png
  search: 
    type: textbox

  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
      - icon: envelope
        href: mailto:chyrwang@gmail.com
    left: "Chaoyue Wang {{< fa solid copyright >}} 2023. Proudly Built with Quarto and {{< fa heart >}} through RStudio."
  
  navbar:
    title: "[**Chaoyue R. Wang**]{.smallcaps}"
    logo: icon.png
    background: light
    foreground: secondary
    right:
      - href: index.qmd
        text: "{{< fa solid circle-user >}} About"
      - href: research.qmd
        text: "{{< fa cube >}} Research"
      - href: data.qmd
        text: "{{< fa database >}} Data"
      - href: software.qmd
        text: "{{< fa solid floppy-disk >}} Software"
      # - href: graphics.qmd
      #   text: "{{< fa chart-bar >}} Graphics"
      - href: posts.qmd
        text: "{{< fa solid fire >}} Posts"
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
      - icon: envelope
        href: mailto:chyrwang@gmail.com

    # left:
    # - icon: twitter
    #   href: https://twitter.com/raphael_cwang
    # - icon: github
    #   href: https://github.com/Raphaellie
    # - icon: envelope
    #   href: mailto:chyrwang@gmail.com

format:
  html:
    theme: [cosmo,light.scss]
      # light: [cosmo,light.scss]
      # dark:  [lumen,light.scss]
    fontcolor: "#222222"
    css: styles.css


editor: visual