project:
  type: website
  resources: 
  - "assets/"
  - "research/"

website:
  title: "CHAOYUE"
  description: "Chaoyue Wang's Personal Website"
  favicon: assets/images/icon.png
  search: 
    type: overlay

  page-footer:
    left: "{{< fa brands creative-commons >}} 2022-2023 CHAOYUE WANG"
    center: 
      - icon: envelope-fill
        href: mailto:chyrwang@gmail.com
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
    background: light
  navbar:
    title: "[**Chaoyue Wang**]{.smallcaps}"
    logo: assets/images/icon.png
    background: light
    foreground: 'black'
    pinned: true
    left:
      - href: index.qmd
        text: "About" # {{< fa solid circle-user >}} 
      - href: research.qmd
        text: "Research" # {{< fa cube >}}
      # - href: data.qmd
        # text: "Data" # {{< fa database >}}
      - href: software.qmd
        text: "Software" # {{< fa solid floppy-disk >}} 
      - href: posts.qmd
        text: "Blog" # {{< fa solid fire >}} 
      # - href: graphics.qmd
      #   text: "{{< fa chart-bar >}} Graphics"
    tools:
      - icon: envelope-fill
        href: mailto:chyrwang@gmail.com
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie


format:
  html:
    theme: lumen
    linkcolor: $primary
    fontsize: 100% # 95%

editor: visual