project:
  type: website
  resources: 
  - "assets/"
  - "research/"

website:
  title: "CHAOYUE"
  description: "Chaoyue Wang's Personal Website"
  favicon: icon.png
  search: 
    type: textbox

  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/raphael_cwang
      - icon: github
        href: https://github.com/Raphaellie
      - icon: envelope
        href: mailto:chyrwang@gmail.com
    left: "Chaoyue Wang {{< fa solid copyright >}} 2023. Proudly Built with Quarto and {{< fa heart >}} through RStudio."
  
  navbar:
    title: "[**Chaoyue**]{.smallcaps}"
    logo: icon.png
    background: light
    # foreground: dark
    pinned: true
    # left:
    #   - icon: twitter
    #     href: https://twitter.com/raphael_cwang
    #   - icon: github
    #     href: https://github.com/Raphaellie
    #   - icon: envelope
    #     href: mailto:chyrwang@gmail.com
    left:
      - href: index.qmd
        text: "About" # {{< fa solid circle-user >}} 
      - href: research.qmd
        text: "Research" # {{< fa cube >}}
      # - href: data.qmd
        # text: "Data" # {{< fa database >}}
      - href: software.qmd
        text: "Software" # {{< fa solid floppy-disk >}} 
      # - href: graphics.qmd
      #   text: "{{< fa chart-bar >}} Graphics"
      - href: posts.qmd
        text: "Posts" # {{< fa solid fire >}} 


    # left:
    # - icon: twitter
    #   href: https://twitter.com/raphael_cwang
    # - icon: github
    #   href: https://github.com/Raphaellie
    # - icon: envelope
    #   href: mailto:chyrwang@gmail.com

format:
  html:
    theme: flatly
    # fontcolor: "#222222"
    linkcolor: $info
    fontsize: 100%
    backgroundcolor: white
    # css: styles.css

editor: visual