---
title: "{{< fa database >}} Data"
nocite: '@*'
toc: true
csl: econometrics.csl
---

## Party Images in Congressional Districts

Nationally, the Republican Party is predominantly white while the Democrat Party owes a larger section of its electoral base to the support among racial minorities. Distinct on the nationwide level, what are the local variations of racialized imageries of the two major parties? Combining 2016 and 2020 Cooperative Congressional Studies, this dataset details the racial compositions of Democratic and Republican partisans at the level of congressional district. For each congressional district, I break up its Republican and Democratic partisans by four racial groups: non-Hispanic whites, Hispanics, blacks, and others. Considering the fact that racial composition of any party in a district is generally conditioned by the racial structure of the local population, I match this dataset with American Community Survey five-year statistics on district-level racial demographics. Additional codes that connect observations to the shape files of congressional districts are also provided so that users can conveniently visualize the geographic pattern of party imageries across the United States.

[Dataverse](https://dataverse.harvard.edu){.btn .btn-outline-info .btn-sm role="button"} [GitHub](https://dataverse.harvard.edu){.btn .btn-outline-success .btn-sm role="button"}

## Racial Compositions of Local Police Officers

Representative bureaucracy, where the racial composition of government employees fairly reflects the racial landscape of the population they work to serve, has been theorized to foster better governance due to the diverse experiences it brings into decision making, and the symbolic proximity it builds with the served public. This said, are the tensions between policing agencies and the served neighbors a result of skewed representation in their workforce? To help address questions like such, this dataset utilizes the 2016 Law Enforcement Management and Administrative Statistics (LEMAS), a nationally representative sample of over 3,000 law enforcement agencies across many levels. I aggregate its race-gender count of police officers at the agency level, calculate the shares of each racial group (non-Hispanic white/Hispanic/black/other), and finally measure its descriptive representation quality by merging the agencies with the ACS demographic statistics of the locality it serves. Representation of a racial group within an agency is approached by the difference between its share in police officers and its percentage in local population. Additional \`R\` codes that helps to visualize the spatial distribution of the departments sampled are also provided.

[Dataverse](https://dataverse.harvard.edu){.btn .btn-outline-info .btn-sm role="button"} [GitHub](https://dataverse.harvard.edu){.btn .btn-outline-success .btn-sm role="button"}
