---
title: "{{< fa burst >}} Research "
fig-cap-location: margin
toc: true
toc-depth: 3
editor_options: 
  chunk_output_type: console
---

Both in the United States and around the globe, political cleavages along group boundaries increasingly impose an obstruction on democratic governance. I'm interested in the relationship between racial identities and political behavior in the context of American Politics. Specifically, my research revolves around the two bundles of questions:

-   **Identities** {{< fa right-long >}} **Politics:** How racial identities shape the ways people perceive and respond to the political world? Through what mechanisms---cultural, psychological, and institutional--are racial identities endowed with political implications? What will the current political polarization look like when construed through a perspective that centers on the role of racial identities?

-   **Politics** {{< fa right-long >}} **Identities:** How do people's politics mold their social identities in return? How do people reconcile the tensions between their political and social selves? For people embodying unusual combinations of politics and identities, like black Republicans or white Evangelical Democrats, which side will triumph in this internal struggle? Or is there a struggle at all?

### Open Science

I believe that research should be as reproducible as possible, so I try to always publish my source code for all my projects on my [GitHub](https://github.com/dsanchezp18) and [RPubs](https://github.com/dsanchezp18) sites. Further, along with very good academics at LIDE, I work on research and projects that can help the development of my home country, Ecuador. Some of the work that I've done with LIDE can be seen below or also at the organization's blog, [El Quantificador](https://elquantificador.org/).

## Working Papers

### Blues in Colors: Police Violence, Racial Representation, and White Attitude Change

-   Sánchez Pazmiño, D. H. (2022). Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery. X-Pedientes Económicos, 6(14), 65--82.

-   Source code posted in a [GitHub repository](https://github.com/dsanchezp18/covidvax-econrecovery-paper) and an RMarkdown notebook posted which was also posted in [RPubs](https://rpubs.com/dsanchezp998/covidvax).

```{=html}
<a href="about.html"><button type="button" class="btn btn-primary btn-sm">PDF</button></a>
<button type="button" class="btn btn-info btn-sm">HTML</button>
<button type="button" href="blog.html"  class="btn btn-secondary btn-sm">GitHub</button>
```
### See the Other Side: Local Party Images and Affective Polarization

Leveraging variations of racialized party imageries at the level of congressional district from 2016 to 2020.

-   Capstone project presented for the obtainment of the Bachelor of Arts in Economics degree at USFQ. Awarded best USFQ undergraduate capstone project for the Fall 2021 semester by the School of Economics faculty. Submitted to the [Philosophy, Politics and Economics Review](https://pressbooks.lib.vt.edu/pper/front-matter/introduction/).

-   [Presented](files/research/hbc-pres.pdf) a working paper version at the USFQ School of Economics Undergraduate Conferences Fall 2021 on December 12th, 2021.

-   Working paper available [here](files/research/hbc-v2.pdf). Initial version submitted to USFQ capstone project's DSpace available [here](https://repositorio.usfq.edu.ec/handle/23000/11202). As of July 2022, a [GitHub repository](https://github.com/dsanchezp18/hbc-v2) includes source code to reproduce all[^1] of the paper's prose and R code. Spanish version coming in the future.

[^1]: Except one graph, due to data copyright reasons, but I do share some code that can make this graph more or less reproducible for people with access to the data. See the repository for details.

```{=html}
<a href="about.html"><button type="button" class="btn btn-primary btn-sm">PDF</button></a>
<button type="button" class="btn btn-info btn-sm">HTML</button>
<button type="button" href="blog.html"  class="btn btn-secondary btn-sm">GitHub</button>
```
### Break the Party Images? The Electoral Impact of Minority Republican Candidates

-   Sánchez Pazmiño, D. H. (2022). Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery. X-Pedientes Económicos, 6(14), 65--82.

-   Source code posted in a [GitHub repository](https://github.com/dsanchezp18/covidvax-econrecovery-paper) and an RMarkdown notebook posted which was also posted in [RPubs](https://rpubs.com/dsanchezp998/covidvax).

## Works in Progress

### Follow the Party: Static and Dynamic Shifting of Identities toward Party Prototypes

-   Sánchez Pazmiño, D. H. (2022). Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery. X-Pedientes Económicos, 6(14), 65--82.

-   Source code posted in a [GitHub repository](https://github.com/dsanchezp18/covidvax-econrecovery-paper) and an RMarkdown notebook posted which was also posted in [RPubs](https://rpubs.com/dsanchezp998/covidvax).
