---
title: "{{< fa window-restore >}} Software"
toc: true
csl: econometrics.csl
---

Here I have compiled a list or a commented bibliography, if you will, of resources that I have found useful along the course of my academic studies. By no means I am an expert on these topics but I do believe that these will help some people out. All efforts that I've dedicated to this page are dedicated to the memory of my grandfather, Jorge Pazmiño. Do not hesitate to contact me for suggestions and comments about these.

## `{RaPhlot}`

R through RStudio, one of my longtime friends. Here you will find a list of resources which I believe can help you get started on your adventures with this marvelous software. It should be noted that I am including these resources with a practical rather than technical approach, which might be a little biased toward econometrics, so it is possible that people on other fields find other resources more helpful.

-   **Book**: [R for Data Science](https://r4ds.had.co.nz/) (R4DS) by Hadley Wickham and Garrett Grolemund

Probably the best introduction to the sofware that exists today. It has been endlessly recommended by all sorts of experts on R, and it is probably because it is a clear and practical guide on how to use R for all sorts of stuff (although the title says specifically data science I strongly believe this intro is fit for *anybody* who wants to use R). It will teach you what R is, what it isn't and what it does best. It is a crash course on five major functions that the language has which are Wrangle, Program, Explore, Model and Communicate. However, because it is an introductory textbook, you'll feel that it only scratches the surface on these three things. In my opinion the "wrangle" part is pretty comprehensive, but if you need more, you'll have to go to other resources, specially for the "Communicate" part. The only difficulty you might find with this book is installing the software, but the next resource will help you with that.

-   **Video series**: [Getting Started with R-Series I](https://www.youtube.com/playlist?list=PLqzoL9-eJTNARFXxgwbqGo56NtbJnB37A) (and probably the rest of the channel) by Mike Marin & Ladan Hamadani

A great tutorial series and overall a great [YouTube channel](https://www.youtube.com/c/marinstatlectures/featured), probably best for those that prefer learning by watching than by reading. Also, I believe that at least for installing a distribution of R and the RStudio IDE it is better to watch videos of other people doing so than reading it. The installation of the software might be one of the complications that R has compared to other software. The tutorial is done on a Mac, but as of right now I have not found that the installation process for a Windows computer is terribly different.

## Some extra advice

Working with R throughout my life as a student and for my personal project, I've met with endless issues. I've been able to solve most of them by googling my question and reading other people's Stack Overflow's questions, or reading books. However, there have been complicated problems which have had rather difficult solutions. In this section I'd like to give some unsolicited advice for you to not run into these problems or how to solve them efficiently if you do.

### Survey data and Binary-Outcome Models

During the data analysis for my capstone project, I worked extensively with survey data and eventually got to running binary-outcome models, namely logit and probit models, with the data. In the literature that used the datasets I was using, it was standard practice to run survey-weighted models to get complex sample-adjusted standard errors and adjusted coefficients. I had no trouble doing this using the *survey* package in R, however, I ran into trouble when I wanted to calculate average partial effects- it was impossible to do so with both the `margins()` or the `marginaleffects()` functions (both have their package named after themselves.).

After much asking around and reading documentation, I found two solutions. The first one is complex and clunky, and not so effective, but it works. The whole thing is described in this [Stack Overflow question](https://stackoverflow.com/questions/68869935/reporting-average-marginal-effects-of-a-survey-weighted-logit-model-with-r/68873977#68873977) that I made when I became desperate one time at 3 am.

The second solution is the one that definitely solved the issue and I discovered it only recently. It is possible to calculate average partial effects of the models that had given me issues in the past when I *changed the data type of certain variables*. Since I had imported my data from Stata files (`.dat` files) using the *haven* package, when I ran `class()` on certain variables I found that it had `double` as the data type. I found that changing the data type to `integer` or `numeric` using the `as.*` functions solved the issue, now, running `marginaleffects()` on the model objects with the updated variables caused no issues. A certainly strange problem; I might write about it on the [Posts](posts_home.qmd) section and/or contribute to [LOST](https://lost-stats.github.io/) with this info.
